version = 3.6.0

align.preset = more    // For pretty alignment.
maxColumn = 100

runner.dialect = scala3

align {
  tokens.add = ["=", "<-", "<--"]
}
maxColumn = 120
rewrite.rules = [SortImports, RedundantBraces, RedundantParens, PreferCurlyFors]

project.excludeFilters = [
  node_modules
]
