name: Deploy demo website

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up sbt
        uses: sbt/setup-sbt@v1

      - name: Compile
        run: sbt compile

      - name: Run tests
        run: sbt test

      - name: Build game
        run: sbt buildFrontend

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: dist/
          destination-github-username: 'sherpal'
          destination-repository-name: 'mad-the-game'
          user-email: antoine.doeraene@gmail.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: master
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
