name: Deploy website

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up sbt
        uses: sbt/setup-sbt@v1

      - name: Compile
        run: sbt compile

      - name: Run tests
        run: sbt test

      - name: Build game
        run: sbt buildFrontend

on:
  push:
    branches:
      - '!main'
